ALTER TABLE appointments DROP CONSTRAINT appointments_new_staff_id_fkey;
ALTER TABLE appointments DROP CONSTRAINT appointments_staff_id_fkey;
ALTER TABLE appointments ADD CONSTRAINT appointments_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES profiles(id);
ALTER TABLE appointments DROP CONSTRAINT appointments_new_created_by_fkey;
ALTER TABLE appointments DROP CONSTRAINT appointments_created_by_fkey;
ALTER TABLE appointments ADD CONSTRAINT appointments_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE staff_schedules DROP CONSTRAINT staff_schedules_new_staff_id_fkey;
ALTER TABLE staff_schedules DROP CONSTRAINT staff_schedules_staff_id_fkey;
ALTER TABLE staff_schedules ADD CONSTRAINT staff_schedules_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES profiles(id);
ALTER TABLE payment_transactions DROP CONSTRAINT payment_transactions_new_staff_id_fkey;
ALTER TABLE payment_transactions DROP CONSTRAINT payment_transactions_staff_id_fkey;
ALTER TABLE payment_transactions ADD CONSTRAINT payment_transactions_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES profiles(id);
ALTER TABLE payment_transactions DROP CONSTRAINT payment_transactions_new_settled_by_fkey;
ALTER TABLE payment_transactions DROP CONSTRAINT payment_transactions_settled_by_fkey;
ALTER TABLE payment_transactions ADD CONSTRAINT payment_transactions_settled_by_fkey FOREIGN KEY (settled_by) REFERENCES profiles(id);
ALTER TABLE refunds DROP CONSTRAINT refunds_new_refunded_by_fkey;
ALTER TABLE refunds DROP CONSTRAINT refunds_refunded_by_fkey;
ALTER TABLE refunds ADD CONSTRAINT refunds_refunded_by_fkey FOREIGN KEY (refunded_by) REFERENCES profiles(id);
ALTER TABLE activity_log DROP CONSTRAINT activity_log_new_user_id_fkey;
ALTER TABLE activity_log DROP CONSTRAINT activity_log_user_id_fkey;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
DROP TABLE IF EXISTS staff CASCADE;
NOTIFY pgrst, 'reload schema';
